services:
  postgres:
    container_name: postgres
    image: postgres:16
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    ports:
      - "${POSTGRES_PORT}:5432"
    volumes:
      - ./scripts:/docker-entrypoint-initdb.d
  
  spark_job:
    container_name: spark_job
    build:
      context: ./ETL
      dockerfile: Dockerfile
    environment:
      DB_URL: "jdbc:postgresql://postgres:5432"
      DB_USER: ${POSTGRES_USER}
      DB_PASSWORD: ${POSTGRES_PASSWORD}
    depends_on:
      - postgres